// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: events.sql

package db

import (
	"context"
	"time"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
	"name", "start_date", "end_date", "link", "description"
) VALUES ($1, $2, $3, $4, $5) RETURNING name, start_date, end_date, link, description
`

type CreateEventParams struct {
	Name        string
	StartDate   time.Time
	EndDate     time.Time
	Link        string
	Description string
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.Link,
		arg.Description,
	)
	var i Event
	err := row.Scan(
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Link,
		&i.Description,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT name, start_date, end_date, link, description FROM events LIMIT 1 OFFSET $1
`

func (q *Queries) GetEvent(ctx context.Context, offset int32) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, offset)
	var i Event
	err := row.Scan(
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Link,
		&i.Description,
	)
	return i, err
}

const getEventCount = `-- name: GetEventCount :one
SELECT COUNT(*) FROM events
`

func (q *Queries) GetEventCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getEventCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
