// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"time"
)

type Event struct {
	Name        string
	StartDate   time.Time
	EndDate     time.Time
	Link        string
	Description string
}

type User struct {
	ID             string
	HashedPassword string
	FullName       string
	CreatedAt      time.Time
}
