// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetEvent(ctx context.Context, offset int32) (Event, error)
	GetEventCount(ctx context.Context) (int64, error)
	GetUser(ctx context.Context, id string) (User, error)
}

var _ Querier = (*Queries)(nil)
